hoomanjafari/aboutus/urls.py
from django.urls import path
from . import views

app_name = 'about-us'
urlpatterns = [
    path('', views.AboutUsView.as_view(), name='about_us')
]

hoomanjafari/article/urls.py
from django.urls import path
from . import views


app_name = 'article'
urlpatterns = [
    path('', views.ArticleView.as_view(), name='article'),
]

hoomanjafari/contact/urls.py
from django.urls import path
from . import views


app_name = 'contact'
urlpatterns = [
    path('', views.ContactView.as_view(), name='contact'),
]

hoomanjafari/cv/urls.py
from django.urls import path
from . import views

app_name = 'cv'
urlpatterns = [
    path('', views.CvView.as_view(), name='cv_page'),
]

hoomanjafari/hoomanjafari/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('index.urls', namespace='home')),
    path('cv/', include('cv.urls', namespace='cv')),
    path('about-us/', include('aboutus.urls', namespace='about-us')),
    path('contact/', include('contact.urls', namespace='contact')),
    path('article/', include('article.urls', namespace='article')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

hoomanjafari/index/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.Home.as_view(), name='home'),
    path('search-page/', views.SearchView.as_view(), name='search-page'),
]

hoomanjafari/aboutus/models.py
from django.db import models

# Create your models here.

hoomanjafari/article/models.py
from django.db import models


class Article(models.Model):
    image = models.ImageField(upload_to='img/%y')
    tag = models.CharField(max_length=9)
    subject = models.CharField(max_length=40)
    body = models.TextField(max_length=160)

    def __str__(self):
        return f'{self.tag} - {self.subject}'

hoomanjafari/contact/models.py
from django.db import models


class Contact(models.Model):
    subject = models.CharField(max_length=333)
    email = models.EmailField()
    number = models.PositiveIntegerField(blank=True, null=True)
    body = models.TextField()

    def __str__(self):
        return f'{self.email} - {self.subject}'

hoomanjafari/cv/models.py
from django.db import models


class MyCv(models.Model):
    img = models.ImageField(upload_to='img/%y')
    body = models.CharField(max_length=300)

    def __str__(self):
        return f'{self.body[:20]}'

hoomanjafari/index/models.py
from django.db import models

# Create your models here.

hoomanjafari/contact/forms.py
from django import forms
from .models import Contact


class ContactForm(forms.ModelForm):
    class Meta:
        model = Contact
        fields = '__all__'

        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '... موضوع'}),
            'email': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '... ایمیل'}),
            'number': forms.TextInput(attrs={'class': 'form-control', 'placeholder': '... شماره تماس' }),
            'body': forms.Textarea(attrs={'class': 'form-control', 'style': 'resize:none;', 'placeholder': ' ... پیام خود را بنویسید'}),
        }
        labels = {
            'subject': '',
            'email': '',
            'number': '',
            'body': ''
        }

hoomanjafari/aboutus/views.py
from django.shortcuts import render
from django.views import View


class AboutUsView(View):
    def get(self, request):
        return render(request, 'aboutus/about_us(front).html')

hoomanjafari/article/views.py
from django.shortcuts import render
from django.views import View
from .models import Article


class ArticleView(View):
    def get(self, request):
        article = Article.objects.all()
        return render(request, 'article/article.html', {'article': article})

hoomanjafari/contact/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from .forms import ContactForm
from .models import Contact


class ContactView(View):
    def get(self, request):
        form = ContactForm()
        return render(request, 'contact/contact.html', {'form': form})

    def post(self, request):
        form = ContactForm(self.request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'اطلاعات شما ثبت شد بزودی با شما تماس میگیرم', 'success')
            return redirect('contact:contact')
        else:
            return render(request, 'contact/contact.html', {'form': form})

hoomanjafari/cv/views.py
from django.shortcuts import render
from django.views import View
from .models import MyCv


class CvView(View):
    def get(self, request):
        cv = MyCv.objects.all()
        return render(request, 'cv/cv.html', {'cv': cv})

hoomanjafari/index/views.py
from django.shortcuts import render
from django.views import View


class Home(View):
    def get(self, request):
        return render(request, 'index/index.html')


class SearchView(View):
    def get(self, request):
        return render(request, 'index/search_page.html')

hoomanjafari/aboutus/templates/aboutus/about_us(front).html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>درباره ما</title>
    <link rel="stylesheet" href="/static/about_us.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/Fonts/font-awesome-4.7.0/css/font-awesome.min.css">
</head>

<body>
    {% include 'includes/search_box.html' %}
    <header class="about-us-header-bg">
        {% include 'includes/navbar.html' %}
        <div class="clear-fix"></div>
        <div class="content">
            <h3 class="mb-5">جلوتر بمان</h3>
            <p class="mb-5">
                ما محصولات نرم افزاری را برای دسکتاپ، وب، موبایل و
                دستگاه های متصل طراحی و می سازیم
                و برای برتری در اجرا ارزش قائل هستیم و راه حل های نرم افزاری پیچیده را به مشاغل در سراسر
                جهان
                ارائه می دهیم
            </p>
            <p>
                ماموریت ما کمک به کسب‌وکارها برای ساختن آینده و رشد بیشتر به شرکت‌های برجسته، با استفاده از فناوری‌های
                پیشرفته و بهترین شیوه‌ها در توسعه نرم‌افزار است.
            </p>
        </div>
        <div></div>
        <div class="clear-fix"></div>
    </header>

    <div class="about-us-content">
        <div class="vision-content">
            <article>
                <h3 class="mb-5">
                    دیدگاه ما
                </h3>
                <p class="mb-5">
                    ما دنیایی را تصور می کنیم که در آن همه جنبه های زندگی ما با محصولات نرم افزاری درجه یک، از راه حل
                    های کاربردی اینترنت اشیا گرفته تا برنامه های موبایل مؤثر و ابزارهای آنلاین ارزشمند، بهبود می یابد.
                </p>
                <p class="mb-5">
                    ما از اعتراف به این که توسط کلیشه صنعت تبدیل شدن جهان به مکانی بهتر، یک راه حل نرم افزاری در یک زمان
                    هدایت می شویم، ابایی نداریم.
                </p>
                <p class="mb-5">
                    ما با پشتکار نقش خود را در تحقق این چشم انداز ایفا می کنیم، چه با توسعه پروژه های داخلی یا کار برای
                    مشتریان خود، تا ایده های آنها را به واقعیت تبدیل کنیم.
                </p>
            </article>
            <img alt="content-vision" src="/static/images/content-vision.jpg">
        </div>


    </div>

    {% include 'includes/footer.html' %}
</body>

</html>

hoomanjafari/article/templates/article/article.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>مقاله</title>
    <link rel="stylesheet" href="/static/article.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/Fonts/font-awesome-4.7.0/css/font-awesome.min.css">
</head>

<body>
    <div class="app-article">
        {% include 'includes/search_box.html' %}
        {% include 'includes/navbar.html' %}
        <div class="article-content">

            <h3>
                مطالعه مقالات
            </h3>

            {% for i in article %}
            <div class="article-item">
                <div class="img-subject">
                    <img src="{{ i.image.url }}">

                    <div class="article-mini-box">
                        <p>{{ i.tag }}</p>
                    </div>
                </div>
                <h2>
                    {{ i.subject }}
                </h2>

                <p class="article-item-p">
                    {{ i.body }}
                </p>
            </div>
            {% endfor %}

        </div>

        {% include 'includes/footer.html' %}
    </div>

</body>

</html>

hoomanjafari/contact/templates/contact/contact.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>contact</title>
    <link rel="stylesheet" href="/static/contact.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/Fonts/font-awesome-4.7.0/css/font-awesome.min.css">
</head>
<body>
    <div class="contact-app">
        {% include 'includes/search_box.html' %}
        <header>
            {% include 'includes/navbar.html' %}
        </header>
        <div class="contact-content">
            <h3>اطلاعات خود را برای مشاوره با من وارد کنید</h3>
            {% if messages %}
                {% for i in messages %}
                    <p class="alert alert-{{ i.tags }} ">{{ i.message }}</p>
                {% endfor %}
            {% endif %}
            <form method="post" class="contact-form">
                {% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">ارسال</button>
            </form>
        </div>

        {% include 'includes/footer.html' %}
    </div>
</body>
</html>

hoomanjafari/cv/templates/cv/cv.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="/static/cv.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/Fonts/font-awesome-4.7.0/css/font-awesome.min.css">
    <title>my CV</title>
</head>

<body>
    <div class="cv-app">
        {% include 'includes/search_box.html' %}
        <header class="cv-header">
            {% include 'includes/navbar.html' %}
            <div class="cv-header-content">
                <article class="cv-article">

                    <h3 class="mb-5">خوش آمدید</h3>
                    <div class="cv-article-p">
                        <div class="cv-wr"></div>
                        <p class="mb-5">نام من هومان است، من یک توسعه دهنده فرانت اند مستقر در تورکی، دوون، بریتانیا
                            هستم.
                            من بسیاری را
                            توسعه داده ام
                            انواع فرانت‌اند از برنامه‌های معروف دی‌جی تا پلتفرم‌های رزرو تجارت الکترونیک
                        </p>
                        <p>
                            من علاقه زیادی به رابط های پیشرفته، پیکسلی، زیبا دارم
                        </p>
                    </div>
                </article>
            </div>
        </header>

        <div class="cv-content">
            <h3><i class="fa fa-arrow-down"></i> نمونه کار ها</h3>
            {% for i in cv %}
            <div class="cv-item">
                <img src="{{ i.img.url }}" class="">
                <div>
                    <p>
                        {{ i.body }}
                    </p>
                </div>
            </div>
            {% endfor %}
        </div>

        {% include 'includes/footer.html' %}
    </div>

</body>

</html>

hoomanjafari/index/templates/index/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hooman Jafari</title>
    <link rel="stylesheet" href="/static/css.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/Fonts/font-awesome-4.7.0/css/font-awesome.min.css">
</head>

<body>
    <div class="app">

        {% include 'includes/search_box.html' %}
        <header class="header-bg">
            {% include 'includes/navbar.html' %}

            <div class="header-content">
                <article>
                    <h2 class="header-content-header-text">
                        برنامه نویسی سایت
                    </h2>
                    <h2 class="header-content-header-text">
                        به همراه کیفیت و تعهد
                    </h2>
                    <p class="lh-base mt-5 header-content-text">
                        من برنامه نویس سایت هستم و به مدت تقریبا یک سال هست که با این حرفه اشنا شدم و اموزش دیدم
                        داخل این سایت میتونی پرژه های که انجام دادم رو ببینی و باهام در ارتباط باشی
                    </p>
                    <a href="{% url 'contact:contact' %}" class="contaxt-btn btn btn-danger">مشاوره با ما</a>
                </article>
            </div>
        </header>

        <div class="content">
            <div class="content-body">
                <div class="left-side position-relative">
                    <div class="wr position-absolute"></div>
                    <div class="left-side">
                        <div class="mb-5">
                            <h2>
                                ارامش خاطر داشته باشین با ما
                            </h2>
                        </div>
                        <h5 class="lh-base">
                            ما محصولات نرم افزاری را برای دسکتاپ، وب، موبایل و
                            دستگاه های متصل طراحی و می سازیم
                            و برای برتری در اجرا ارزش قائل هستیم و راه حل های نرم افزاری پیچیده را به مشاغل در سراسر
                            جهان
                            ارائه می دهیم
                        </h5>
                    </div>
                </div>
                <div class="right-side">
                    {% load static %}
                    <img alt="rocket" class="rocket-img" src="/static/images/rocket.PNG">
                </div>
            </div>

            <div class="content-article">
                <div class="box-row-1">
                    <div class="box-1 position-relative box-1-img">
                        <article class="box-article position-absolute">
                            <h3 class="box-h3-size">با خیال راحت هر انتظاری از سایت خود دارید رو به ما بسپارید</h3>
                        </article>
                    </div>

                    <div class="box-2 position-relative box-2-img">
                        <article class="box-article position-absolute">
                            <h3 class="box-h3-size">ما برای ساختن نرم افزار پیچیده شما تلاش بیشتری می کنیم
                            </h3>
                        </article>
                    </div>
                </div>

                <div class="bow-row-2">
                    <div class="box-3 position-relative box-3-img">
                        <article class="position-absolute box-article">
                            <h3 class="box-h3-size">ما سایت و وب اپلیکیشن های شما را می سازیم که اهداف تجاریتان را
                                برآورده می کند</h3>
                        </article>
                    </div>

                    <div class="box-4 position-relative box-4-img">
                        <article class="position-absolute box-article">
                            <h3 class="box-h3-size">نوبت شماست که ما را به چالش بکشید</h3>
                        </article>
                    </div>
                </div>
            </div>

            <div class="content-body-2">
                <div class="left-side position-relative">
                    <div class="wr position-absolute"></div>
                    <div class="left-side">
                        <div class="mb-5">
                            <h2>
                                ما مشکلات را حل می کنیم
                            </h2>
                        </div>
                        <h5 class="lh-base">
                            ما با راه‌حل‌های خلاقانه و جذاب، مرزها را پشت سر می‌گذاریم، در حالی که به سخت‌ترین نیازها با
                            دقت و تفکر عمیق پاسخ می‌دهیم.
                        </h5>
                    </div>
                </div>
                <div class="right-side r-s-m">
                    <img class="solving-img" src="/static/images/solveing problems.PNG">
                </div>
            </div>
        </div>

        {% include 'includes/footer.html' %}
    </div>

    <script>
        function HiddenSearch() {
            document.querySelector('.search-box').style.display = 'none'
        }
    </script>
</body>

</html>

hoomanjafari/index/templates/index/search_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>search</title>
    <link rel="stylesheet" href="/static/css.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/Fonts/font-awesome-4.7.0/css/font-awesome.min.css">
</head>
<body>

    <div class="app-search">
        {% include 'includes/search_box.html' %}
        {% include 'includes/navbar.html' %}

        <div class="search-content">
            <h3>در حال حاضر این قسمت غیر فعال هست چون محتوایی برای سرچ نیست</h3>
        </div>

        {% include 'includes/footer.html' %}
    </div>

</body>
</html>

hoomanjafari/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Hooman Jafari</title>
    <link rel="stylesheet" href="/static/css.css">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/Fonts/font-awesome-4.7.0/css/font-awesome.min.css">
</head>
<body>
    {% include 'includes/navbar.html' %}
    {% block content %}
    {% endblock %}
    {% include 'includes/footer.html' %}
</body>
</html>

hoomanjafari/templates/includes/footer.html
<footer class="footer">
    <div class="container">
        <div class="footer-contact">
            <article class="lh-lg">
                <h3 class="mb-5">( ارتباط با من )</h3>
                <h4>
                    ایران,اراک
                    <i class="ms-3 fs-3 fa fa-map-marker"></i>
                </h4>
                <p>+98 937 251 8997<i class="ms-3 fs-1 fa fa-mobile"></i></p>
                <p>hooman.jafari3647@yahoo.com<i class="ms-3 fs-3 fa fa-yahoo"></i></p>
            </article>
        </div>
        <div class="social-media">
            <article >
                <h3 class="">( شبکه های اجتماعی )</h3>
                <a href="https://instagram.com/hooman_jafari76?utm_source=qr&igshid=MW10bzZoMTVsYzJheA==" target="_blank" class="text-white">
                    <i class="fa fa-facebook fs-3"></i>
                </a>
                <a href="https://instagram.com/hooman_jafari76?utm_source=qr&igshid=MW10bzZoMTVsYzJheA==" target="_blank" class="text-white">
                    <i class="fa fa-instagram fs-3"></i>
                </a>
                <a href="https://instagram.com/hooman_jafari76?utm_source=qr&igshid=MW10bzZoMTVsYzJheA==" target="_blank" class="text-white">
                    <i class="fa fa-google-plus fs-3"></i>
                </a>
                <a href="https://instagram.com/hooman_jafari76?utm_source=qr&igshid=MW10bzZoMTVsYzJheA==" target="_blank" class="text-white">
                    <i class="fa fa-twitter fs-3"></i>
                </a>
            </article>
        </div>
    </div>
</footer>

hoomanjafari/templates/includes/navbar.html
<div class="clear-fix"></div>
<nav class="nav-responsive-fixed" id="nav-responsive-fixed">
    <ul class="nav-responsive" id="menu">
        <li class="nav-responsive-icon"><a class="nav-link" href="{% url 'home:home' %}">صفحه نخست</a></li>
        <li class="nav-responsive-icon"><a class="nav-link" href="{% url 'article:article' %}">مقالات</a></li>
        <li class="nav-responsive-icon"><a class="nav-link" href="{% url 'about-us:about_us' %}">درباره ما</a></li>
        <li class="nav-responsive-icon"><a class="nav-link" href="{% url 'cv:cv_page' %}"> نمونه کار ها</a></li>
    </ul>
    <button onclick="HiddenMenu()"></button>
    <div class="clear-fix"></div>
</nav>

<div class="clear-fix"></div>
<nav class="nav-btn-burger">
    <button class="burger-btn" onclick="ShowMenu()"><i class="fa fa-bars fa-2x"></i></button>
</nav>
<div class="clear-fix"></div>

<nav class="nav-style position-relative">
    <div class="clear-fix"></div>
    <div class="nav-left">
        <ul>
            <li class="nav-icon"><a class="nav-link text-info" href="{% url 'home:home' %}"><i class="fa fa-home"></i></a></li>
        </ul>
    </div>
    <div class="nav-right">
        <ul>
            <li class="nav-icon"><a class="nav-link" href="{% url 'article:article' %}">مقالات</a></li>
            <li class="nav-icon"><a class="nav-link" href="{% url 'cv:cv_page' %}"> نمونه کار ها</a></li>
            <li class="nav-icon"><a class="nav-link" href="{% url 'about-us:about_us' %}">درباره ما</a></li>
            <li class="nav-icon"><button onclick="SearchBox()" class="btn"><i class="fs-3 search-icon fa fa-search"></i></button></li>
        </ul>
    </div>
    <div class="clear-fix"></div>
</nav>


<nav class="nav-style-fixed" id="navbar">
    <div class="nav-left">
        <ul>
            <li class="nav-icon"><a class="nav-link text-info" href="{% url 'home:home' %}"><i class="fa fa-home"></i></a></li>
        </ul>
    </div>
    <div class="nav-right">
        <ul>
            <li class="nav-icon"><a class="nav-link" href="{% url 'article:article' %}">مقالات</a></li>
            <li class="nav-icon"><a class="nav-link" href="{% url 'cv:cv_page' %}"> نمونه کار ها</a></li>
            <li class="nav-icon"><a class="nav-link" href="{% url 'about-us:about_us' %}">درباره ما</a></li>
            <li class="nav-icon"><button onclick="SearchBox()" class="btn"><i class="fs-3 search-icon fa fa-search"></i></button></li>
        </ul>
    </div>
</nav>
<script>
    function ShowMenu() {
        document.getElementById("menu").style.width = "calc(100% / 2)"
        document.getElementById("nav-responsive-fixed").style.visibility = "visible"
    }

    function HiddenMenu() {
        document.getElementById("menu").style.width = "0"
        document.getElementById("nav-responsive-fixed").style.visibility = "hidden"
    }

    window.onscroll = function() {scrollFunction()};
    {#window.onscroll = scrollFunction#}

    function scrollFunction() {
      if (document.body.scrollTop > 360 || document.documentElement.scrollTop > 360) {
        document.getElementById("navbar").style.top = "0";
      } else {
        document.getElementById("navbar").style.top = "-90px";
      }
    }

    function SearchBox() {
        document.querySelector('.search-box').style.display = 'block'
    }

</script>

hoomanjafari/templates/includes/search_box.html
<div class="search-box">
    <button class="search-cross" onclick="HiddenSearch()">
        <i class="fa fa-window-close fs-2 text-light"></i>
    </button>
    <div class="search-box-body">
        <h3>متن خود را بنویسید و اینتر کنید</h3>
        <form method="get" action="{% url 'home:search-page' %}">
            {% csrf_token %}
            <input type="search" placeholder="Search ..." class="d-inline-block">
            <button type="submit" class="text-secondary"><i class="fa fa-search fs-1"></i></button>
        </form>
    </div>
</div>

<script>
function HiddenSearch() {
    document.querySelector('.search-box').style.display = 'none'
}
</script>